{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "bf0d588d-5a1e-4258-8e0b-2678556ce572",
   "metadata": {},
   "outputs": [],
   "source": [
    "import logging\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "e19bb45e-1f25-41dc-8a40-79b39faad46c",
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(\"error.txt\", \"r\", encoding=\"utf-8\") as file:\n",
    "    data = file.read()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "b5373804-2b15-421e-8362-6d179aa3e26e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def function_that_does_complicated_stuff():\n",
    "    try: \n",
    "        lll1 = 5\n",
    "        print(llll)\n",
    "    except:\n",
    "        logging.exception(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "0dcfc9e4-3077-4283-a03f-949f620b0b13",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣶⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⠿⠟⠛⠻⣿⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣆⣀⣀⠀⣿⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠻⣿⣿⣿⠅⠛⠋⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢼⣿⣿⣿⣃⠠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣟⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣛⣛⣫⡄⠀⢸⣦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣾⡆⠸⣿⣿⣿⡷⠂⠨⣿⣿⣿⣿⣶⣦⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣾⣿⣿⣿⣿⡇⢀⣿⡿⠋⠁⢀⡶⠪⣉⢸⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⡏⢸⣿⣷⣿⣿⣷⣦⡙⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣇⢸⣿⣿⣿⣿⣿⣷⣦⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣵⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "\n",
      "\n",
      "\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⣼⡟⡀⠀⠀⠀⠀⠁⡴⠋⠉⠉⠙⡧⡄⣆⠀⠀⠀⠀⠀⣠⣯⡇⠀⢀⣴⡶⣿⢍⣄⢄⡀⠀⠀⠀⣶⡆⠀⠀⢀⣤⡖⡀⠀⠀⠀⠀\n",
      "⠀⠈⣿⡿⠿⣿⣷⣆⠀⣟⣏⣀⡀⣀⣠⣇⣷⢻⡆⠀⠀⠀⡼⣿⠋⣀⣦⡋⠯⠉⠀⠁⠃⠷⣽⠀⠀⠀⣿⡇⡠⡿⠉⠁⠀⠀⠀⠀⠀⠀\n",
      "⠀⠐⣿⠅⠀⠈⠻⣿⡄⣯⡟⠛⠛⠛⠛⠛⠋⠉⣷⠀⠀⡟⡽⠁⢀⢕⡷⣷⣶⣶⣶⣶⡶⠛⠂⠀⠀⠀⣿⡏⠋⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⣿⡇⠀⠀⠀⣿⡇⠉⠳⣤⣀⣀⣀⣄⡀⠀⠽⡇⣿⠏⠀⠀⠘⣿⡇⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀⡿⡇⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠉⠀⠀⠀⠀⠱⠇⠀⠀⠈⠙⠛⠛⠉⠁⠀⠀⠿⠃⠀⠀⠀⠀⠙⠛⣿⣓⣶⣦⣤⣤⡄⠀⠀⠀⠀⣷⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⣤⣤⣄⠀⠀⠀⠀⣀⠤⡤⡄⡀⠀⠂⠀⣶⣆⣀⡀⠀⠀⠀⠉⠉⠛⠓⠛⠃⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⣸⠏⡏⠛⢝⣧⠀⠀⣿⠏⠉⠑⠫⣝⡇⠀⠀⡿⡟⠻⠟⣟⣧⡀⠠⣾⣿⠷⢶⣦⣄⠀⠀⢠⡾⠯⣿⣆⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⣿⢆⡃⠀⡠⡟⡄⠀⡧⠃⠀⠀⠀⠠⡇⠀⠀⣿⡇⠀⠀⠩⡏⡇⠀⣿⣿⠀⠀⠉⢻⣷⡄⢿⡇⠀⠸⣿⡀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠣⣕⢟⣛⠟⣧⡇⠀⣻⣏⣆⣢⣔⠋⠁⠀⠀⠛⠿⠀⠀⠀⠃⠃⠀⢻⡿⠀⠀⠀⠈⣿⢿⠈⠛⠿⠟⢹⣷⡀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⣀⡀⠀⠉⣁⡮⡿⠁⠀⠈⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠁⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠈⠃⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠑⠭⠭⠿⠛⠓⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠢⡄⠀⡆⢀⠀⠀⠀⠀⡄⠀⠀⢀⡠⠄⠄⠄⡀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⠛⠛⢿⡆⠀⠀⠀⠯⠋⠀⠀⠩⣿⠀⠀⢀⢾⠇⠁⣀⣥⠶⠓⠻⢯⡲⡌⡱⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡁⠀⠀⠀⡸⣿⠀⠀⠀⣄⠀⠀⠀⠈⣮⠢⠀⣮⠏⠀⢨⣯⣧⣆⣒⣨⣡⣯⠏⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠈⠙⠦⣤⡤⠟⢝⡄⠀⠀⠧⠅⠀⠀⠀⣟⡄⡟⠅⠀⠀⠀⡏⣇⠈⠙⠓⠓⠁⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⢟⡅⠀⠀⠘⡇⠀⠀⠀⠈⠿⠃⠀⠀⠀⠀⠉⠻⣿⣦⣤⣤⣔⣯⡍⠁⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⡶⣄⢀⠀⠀⢀⡟⡑⠁⠀⠀⠀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠋⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠋⠭⠬⠋⠋⠉⠀⠀⠀⠀⠀⠀⠀⢀⡀⡀⡀⠀⠀⠀⠀⠀⢀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠲⡦⡀⠀⠀⢀⡷⠋⣴⠃⠁⠁⡇⠻⣄⠀⠀⠀⣸⢸⠹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⡦⣰⠏⠁⠀⢿⣀⢀⣴⠇⠀⠈⢯⣆⡦⣯⡋⠞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣽⠋⠀⠀⠀⠑⠛⠋⠁⠀⠀⠀⠀⠀⠈⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⢯⠁⠀⠀⠀⢠⡆⠀⠀⠀⡄⠀⠀⠀⣾⡿⠿⠧⢿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠀⠀⠀⠀⣿⡏⠀⠀⠀⣿⡆⠀⠀⣿⣷⠁⡰⠿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠯⣿⣆⡀⣖⡟⠀⠀⠀⢹⣿⡿⠇⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠀⠀⠀⠀⠸⢧⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠤⠞⣋⠉⣿⣯⣿⢿⣖⠦⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠿⣶⣾⣿⣾⣿⣹⣿⣶⣿⣿⣾⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣧⣰⣿⣿⣿⣿⣿⣿⡿⠿⠿⣿⣿⡟⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠟⣠⣿⠟⠋⠉⠀⠈⠀⠀⠀⠀⠘⣿⣧⢣⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⠀⠀⠀⢀⡀⠀⠀⣀⡀⠀⣾⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⡏⠀⢻⣯⡽⢿⡄⠘⢿⡯⠵⢻⣟⡋⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⠼⣧⠀⠉⠀⠀⠀⠁⠀⠀⠀⠀⢨⣿⢳⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢌⢧⣬⠇⠀⠀⠀⠸⠛⠂⠘⠆⢎⡴⣻⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠉⣿⡆⠀⠀⢾⣯⢿⣗⣀⣼⣹⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠸⡟⠀⠀⠀⠟⢲⣶⠶⣿⠍⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⠰⡇⠀⠀⠀⠴⢺⣿⣤⢿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣾⣿⣿⣿⡆⢧⡀⠀⢀⣀⣼⣿⣟⡇⢿⣷⣶⣤⣄⣀⠀⠀⠀⠀⠀⠀\n",
      "⠀⠀⠀⠀⠀⣀⣴⣶⣿⣿⣿⣿⣿⣿⣿⣷⠀⠳⣄⠀⠉⢿⣿⣿⠇⠸⣿⣿⣿⣿⣿⣿⣷⣦⣄⡀⠀\n",
      "⠀⢀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⠆⠙⢦⣀⣨⠗⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⠀\n",
      "⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣀⣠⣤⣀⣉⠀⠀⡀⢠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆\n",
      "⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⢁⣼⠿⢿⣿⣿⣿⠲⠶⠶⠯⢤⣠⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇\n",
      "⠀⡿⣿⣿⣿⣿⣿⣿⣿⡟⣰⢹⣁⡀⠈⠙⣻⣿⣍⣉⣙⣒⣻⠓⢾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏\n",
      "⠀⣷⣾⣿⣿⣿⣿⣿⣿⠁⡇⠀⠉⡀⠙⢿⣿⣿⡧⠤⠤⠭⠭⣌⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇\n",
      "⢀⣿⣿⣿⣿⣿⣿⣿⣿⡟⠁⠀⠀⣇⣤⣾⣿⣿⣗⠒⠒⠲⣶⠦⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnn\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "packages\\tensorflow\\python\\platform\\self_check.py\", line 87, in preload_check\n",
      "    ctypes.WinDLL(build_info.cudnn_dll_name)\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\ctypes\\__init__.py\", line 347, in __init__\n",
      "self._handle = _dlopen(self._name, mode)\n",
      "OSError: [WinError 126] This specified module could not be found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<stdin>\", line 1, in <module>\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\__init__.py\", line 24, in <module>\n",
      "from tensorflow.python import *\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\__init__.py\", line 49, in <module>\n",
      "from tensorflow.python import pywrap_tensorflow\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\pywrap_tensorflow.py\", line 30, in <module>\n",
      "self_check.preload_check()\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-packages\\tensorflow\\python\\platform\\self_check.py\", line 97, in preload_check\n",
      "% (build_info.cudnn_dll_name, build_info.cudnn_version_number))\n",
      "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Note that installing cuDNN is a separate step from installing CUDA, and this DLL is often found in a different directory from the CUDA DLLs. You may install the necessary DLL by downloading cuDNN 6 from this URL: https://developer.nvidia.com/cudnnTraceback (most recent call last):\n",
      "  File \"C:\\Users\\Froilan\\Anaconda3\\envs\\tensorflow-gpu\\lib\\site-\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\lukep\\AppData\\Local\\Temp\\ipykernel_18320\\3666485576.py\", line 4, in function_that_does_complicated_stuff\n",
      "    print(llll)\n",
      "NameError: name 'llll' is not defined\n"
     ]
    }
   ],
   "source": [
    "function_that_does_complicated_stuff()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a0c5747e-b7f4-487a-b862-fd296102a729",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
